### ISSUE TITLE
Carpeta s03t00

### ISSUE THREAD

**Issue by PalyDescouvieres** [disenoudd/ed22017#87]
Nico, aún no haces la carpeta para subir la tarea #3 🐷

**Comment by nicotron** [comment]
Tienes razón, actualizaré ahora el repo con la carpeta, pero el README.md de la misma, que sirve como recuerdo de la tarea, no estará hasta mañana.

**Comment by nicotron** [comment]
Muy bien @PalyDescouvieres por usar los *issues* para documentar un problema del curso, así todos podrán participar e informarse con respecto al curso.

**Comment by PalyDescouvieres** [comment]
:nerd_face: 👍

**Comment by nicotron** [comment]
Tarea lista
